site_name: Gaea Documentation
theme:
  name: readthedocs
  highlightjs: true
  logo: assets/banner.svg
site_favicon: assets/logo.svg
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
  - mkdocs-nav-weight
markdown_extensions:
  - admonition
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js
