site_name: Gaea Documentation
theme:
  name: readthedocs
  highlightjs: true
  logo: assets/banner.svg
  custom_dir: _custom/
site_favicon: assets/logo.svg
plugins:
  - search
  - mkdocs-nav-weight
markdown_extensions:
  - admonition
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js
